{% set version = "14.2.3" %}

package:
  name: reproc
  version: '{{ version }}'

source:
  - url: https://github.com/DaanDeMeyer/reproc/archive/v{{ version }}.tar.gz
    sha256: ea87db7a780a81bc27bce3e6c8e5f31b831fb8a1d06c6b5c2e1c2554d1c55e00

build:
  number: 1

outputs:
  - name: reproc
    script: build_c.sh  # [unix]
    build:
      run_exports:
        - "{{ pin_subpackage('reproc', 'x.x') }}"
    requirements:
      build:
        - {{ compiler("c") }}
        - cmake {{ cmake }}
        - make   # [unix]
    test:
      commands:
        - test -f ${PREFIX}/include/reproc/run.h                          # [unix]
        - test -f ${PREFIX}/lib/libreproc${SHLIB_EXT}                     # [unix]
        - test -f ${PREFIX}/lib/cmake/reproc/reproc-config-version.cmake  # [unix]
        - test ! -f ${PREFIX}/lib/libreproc.a                             # [unix]

  - name: reproc-cpp
    script: build_cpp.sh  # [unix]
    build:
      run_exports:
        - '{{ pin_subpackage('reproc-cpp', 'x.x') }}'
    requirements:
      build:
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
        - cmake {{ cmake }}
        - make   # [unix]
      host:
        - "{{ pin_subpackage('reproc', exact=True ) }}"
      run:
        - "{{ pin_subpackage('reproc', exact=True ) }}"
    test:
      commands:
        - test -f ${PREFIX}/include/reproc++/reproc.hpp               # [unix]
        - test -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}               # [unix]
        - test -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake  # [unix]
        - test ! -f ${PREFIX}/lib/libreproc++.a                       # [unix]

  - name: reproc-static
    script: build_c.sh  # [unix]
    build:
      ignore_run_exports:
        - reproc
    requirements:
      build:
        - '{{ compiler("c") }}'
        - cmake {{ cmake }}
        - make   # [unix]
      host:
        - "{{ pin_subpackage('reproc', exact=True ) }}"
    test:
      commands:
        - test ! -f ${PREFIX}/include/reproc/run.h                          # [unix]
        - test ! -f ${PREFIX}/lib/libreproc${SHLIB_EXT}                     # [unix]
        - test ! -f ${PREFIX}/lib/cmake/reproc/reproc-config-version.cmake  # [unix]
        - test -f ${PREFIX}/lib/libreproc.a                                 # [unix]

  - name: reproc-cpp-static
    script: build_cpp.sh  # [unix]
    build:
      ignore_run_exports:
        - reproc
        - reproc-cpp
    requirements:
      build:
        - '{{ compiler("c") }}'
        - '{{ compiler("cxx") }}'
        - cmake {{ cmake }}
        - make   # [unix]
      host:
        - "{{ pin_subpackage('reproc', exact=True ) }}"
        - "{{ pin_subpackage('reproc-static', exact=True ) }}"
        - "{{ pin_subpackage('reproc-cpp', exact=True ) }}"
    test:
      commands:
        - test ! -f ${PREFIX}/include/reproc++/reproc.hpp                # [unix]
        - test ! -f ${PREFIX}/lib/libreproc++${SHLIB_EXT}                # [unix]
        - test ! -f ${PREFIX}/lib/cmake/reproc++/reproc++-config.cmake   # [unix]
        - test -f ${PREFIX}/lib/libreproc++.a                            # [unix]
        - if exist %LIBRARY_PREFIX%\lib\reproc++_static.lib (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/DaanDeMeyer/reproc
  license_file: LICENSE
  license: MIT
  summary: reproc (Redirected Process) is a cross-platform C/C++ library that simplifies starting, stopping and communicating with external programs.
  dev_url: https://github.com/DaanDeMeyer/reproc

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
